name: fitility
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.1
  firebase_auth:
  google_sign_in: ^4.5.1
  firebase_core: ^0.4.5
  cloud_firestore:
  shared_preferences:
  toast: ^0.1.5
  progress_dialog:
  webview_flutter:
  auto_size_text:
  carousel_pro: ^1.0.0
  fluttertoast: ^7.1.6
  auro_avatar:

  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  
  assets:
   - images/
  
  fonts:
    - family: Rubik
      fonts:
      - asset: fonts/Rubik-Regular.ttf
    - family: Fitility
      fonts:
      - asset: icons/Fitility.ttf