name: fitility
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.1
  firebase_auth:
  google_sign_in: ^4.5.1
  firebase_core: ^0.4.5
  cloud_firestore:
  shared_preferences:
  toast: ^0.1.5
  progress_dialog:
  auro_avatar:
  webview_flutter:
  auto_size_text:

  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
   - images/girl.png
   - images/logo.png
   - images/google.png
   - images/box.png
   - images/pic1.png
   - images/pic2.png
   - images/pic3.png
   - images/meal.png
   - images/line.png
   - images/dumble.png
   - images/lineh.png
   - images/bullet.png
   - images/bar1.png
   - images/circle1.png
   - images/circle2.png
   - images/circle3.png
   - images/circle4.png
   - images/circles.png
   - images/circles1.png
   - images/bar2.png
   - images/lime.png
   - images/breakfast.png
   - images/almond.png
   - images/lunch.png
   - images/crops.png
   - images/Flat.png
   - images/omelette.png
   - images/papaya.png
   - images/water.png
   - images/energy-bar.png
   - images/bottle.png
   - images/banana.png
   - images/cucumber.png
   - images/home.png
   - images/workout.png
   - images/dance.png
   - images/diet.png
   - images/plans.png
  fonts:
    - family: Rubik
      fonts:
      - asset: fonts/Rubik-Regular.ttf
    - family: Fitility
      fonts:
      - asset: icons/Fitility.ttf